env:
    browser: true
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
    - prettier
settings:
    react:
        version: detect
rules:
    linebreak-style:
        - error
        - unix
    react/react-in-jsx-scope: 0
    "@typescript-eslint/explicit-member-accessibility": 
        - error
        - { "overrides": { "constructors": "no-public" } }
    prettier/prettier: error
ignorePatterns:
    - src/**/*generated*
