import type { Metadata } from "next";
import "./globals.css";
import { WeatherProvider } from "@/providers/Weather.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WeatherProvider>{children}</WeatherProvider>
      </body>
    </html>
  );
}
